# Generated by Django 4.2 on 2023-04-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
    ]
